import { today, addDays } from './date.js';
import { uid } from './id.js';

export const getInitialSeedCollections = () => [
  { id: 'starred', name: 'Starred', description: 'Priority & starred problems', color: 'amber' },
  { id: 'blind75', name: 'Blind 75', description: 'Must-do curated coding interview list', color: 'blue' },
  { id: 'top150', name: 'Top Interview 150', description: 'LeetCode Top Interview 150 collection', color: 'emerald' },
];

export const getInitialSeedProblems = () => [
  {
    id: uid(),
    name: 'Number of Islands',
    diff: 'Medium',
    status: 'Solved',
    tags: ['Graphs', 'BFS', 'DFS'],
    collId: 'top150',
    starred: true,
    notes: '## Approach\nUse DFS or BFS to traverse the grid. Mark visited land cells to avoid double counting.\n\n**Time:** O(M*N) | **Space:** O(M*N)',
    platforms: [
      { platform: 'LeetCode', url: 'https://leetcode.com/problems/number-of-islands/' },
      { platform: 'GFG', url: 'https://www.geeksforgeeks.org/problems/find-the-number-of-islands/1' },
    ],
    date: addDays(today(), -1),
    interval: 3,
    nextRev: addDays(today(), 2),
    revCount: 1,
    solvedDate: addDays(today(), -1),
  },
  {
    id: uid(),
    name: 'Coin Change',
    diff: 'Medium',
    status: 'Solved',
    tags: ['Dynamic Programming'],
    collId: 'blind75',
    starred: true,
    notes: '## Approach\nBottom-up DP. Array of size `amount + 1` initialized to `amount + 1`.\n\n**Time:** O(S*n) | **Space:** O(S)',
    platforms: [
      { platform: 'LeetCode', url: 'https://leetcode.com/problems/coin-change/' },
    ],
    date: addDays(today(), -2),
    interval: 3,
    nextRev: addDays(today(), 1),
    revCount: 2,
    solvedDate: addDays(today(), -2),
  },
  {
    id: uid(),
    name: 'Merge K Sorted Lists',
    diff: 'Hard',
    status: 'Solved',
    tags: ['Heap', 'Linked List'],
    collId: 'top150',
    starred: false,
    notes: '## Approach\nUse a min-heap to keep track of the smallest node among the k linked lists.\n\n**Time:** O(N log k) | **Space:** O(k)',
    platforms: [
      { platform: 'LeetCode', url: 'https://leetcode.com/problems/merge-k-sorted-lists/' },
    ],
    date: addDays(today(), -3),
    interval: 5,
    nextRev: addDays(today(), 2),
    revCount: 1,
    solvedDate: addDays(today(), -3),
  },
  {
    id: uid(),
    name: 'Two Sum',
    diff: 'Easy',
    status: 'Solved',
    tags: ['Array', 'Hash Table'],
    collId: 'blind75',
    starred: true,
    notes: '## Approach\nUse a hash map to store the difference between target and current element.\n\n**Time:** O(n) | **Space:** O(n)',
    platforms: [
      { platform: 'LeetCode', url: 'https://leetcode.com/problems/two-sum/' },
    ],
    date: addDays(today(), -5),
    interval: 14,
    nextRev: addDays(today(), 9),
    revCount: 4,
    solvedDate: addDays(today(), -5),
  },
  {
    id: uid(),
    name: 'LRU Cache',
    diff: 'Medium',
    status: 'Attempted',
    tags: ['Design', 'Linked List', 'Hash Table'],
    collId: '',
    starred: false,
    notes: '## Approach\nCombine doubly linked list with hash table for O(1) get and put.',
    platforms: [
      { platform: 'LeetCode', url: 'https://leetcode.com/problems/lru-cache/' },
      { platform: 'GFG', url: 'https://www.geeksforgeeks.org/problems/lru-cache/1' },
    ],
    date: today(),
    interval: 1,
    nextRev: addDays(today(), 1),
    revCount: 0,
  },
  {
    id: uid(),
    name: 'Valid Parentheses',
    diff: 'Easy',
    status: 'Solved',
    tags: ['String', 'Stack'],
    collId: 'blind75',
    starred: false,
    notes: '## Approach\nUse stack to match brackets. Check stack emptiness at end.',
    platforms: [
      { platform: 'LeetCode', url: 'https://leetcode.com/problems/valid-parentheses/' },
    ],
    date: addDays(today(), -10),
    interval: 30,
    nextRev: addDays(today(), 20),
    revCount: 5,
    solvedDate: addDays(today(), -10),
  },
  {
    id: uid(),
    name: 'Median of Two Sorted Arrays',
    diff: 'Hard',
    status: 'Attempted',
    tags: ['Array', 'Binary Search'],
    collId: 'top150',
    starred: true,
    notes: '## Approach\nBinary search on the smaller array partition.\n\n**Time:** O(log(min(m, n)))',
    platforms: [
      { platform: 'LeetCode', url: 'https://leetcode.com/problems/median-of-two-sorted-arrays/' },
    ],
    date: addDays(today(), -15),
    interval: 1,
    nextRev: today(),
    revCount: 1,
  },
  {
    id: uid(),
    name: 'Longest Palindromic Substring',
    diff: 'Medium',
    status: 'Solved',
    tags: ['String', 'Dynamic Programming'],
    collId: '',
    starred: false,
    notes: '## Approach\nExpand around potential center points (odd and even lengths).',
    platforms: [
      { platform: 'LeetCode', url: 'https://leetcode.com/problems/longest-palindromic-substring/' },
    ],
    date: addDays(today(), -20),
    interval: 14,
    nextRev: addDays(today(), -1),
    revCount: 3,
    solvedDate: addDays(today(), -20),
  },
  {
    id: uid(),
    name: 'Climbing Stairs',
    diff: 'Easy',
    status: 'Solved',
    tags: ['Math', 'Dynamic Programming'],
    collId: 'blind75',
    starred: false,
    notes: '## Approach\nFibonacci sequence: dp[i] = dp[i-1] + dp[i-2].',
    platforms: [
      { platform: 'LeetCode', url: 'https://leetcode.com/problems/climbing-stairs/' },
    ],
    date: addDays(today(), -4),
    interval: 7,
    nextRev: addDays(today(), 3),
    revCount: 1,
    solvedDate: addDays(today(), -4),
  },
  {
    id: uid(),
    name: 'Search in Rotated Sorted Array',
    diff: 'Medium',
    status: 'Solved',
    tags: ['Array', 'Binary Search'],
    collId: 'blind75',
    starred: false,
    notes: '## Approach\nModified binary search. Identify which half is sorted, then check target range.',
    platforms: [
      { platform: 'LeetCode', url: 'https://leetcode.com/problems/search-in-rotated-sorted-array/' },
    ],
    date: addDays(today(), -2),
    interval: 3,
    nextRev: addDays(today(), 1),
    revCount: 2,
    solvedDate: addDays(today(), -2),
  },
];

export const getInitialSeedActivity = () => ({
  [today()]: 2,
  [addDays(today(), -1)]: 1,
  [addDays(today(), -2)]: 3,
  [addDays(today(), -4)]: 1,
  [addDays(today(), -5)]: 4,
  [addDays(today(), -7)]: 2,
  [addDays(today(), -10)]: 1,
  [addDays(today(), -15)]: 5,
  [addDays(today(), -20)]: 2,
  [addDays(today(), -25)]: 3,
});
